Repository WhitewaterFoundry/Pengwin, pull requests merged in 2018-11, with the labels that each got.

#140 Fix pip3 path bug
  linux_files/setup
Labels: Bug, To Implement, Undergoing Testing

#144 Some Fixes according to the feedback
  linux_files/setup
Labels: To Implement, Undergoing Testing

#130 Docker Support in wlinux-setup
  linux_files/setup
Labels: Bounty Assigned, To Implement, Undergoing Testing

#173 Set Go language version
  linux_files/setup
Labels: To Implement, Undergoing Testing

#237 Final experimental ARM64 support Pull for 1.1.26
  create-targz-arm64.sh
Labels: To Implement, Undergoing Testing
